CREATE database IF NOT EXISTS COMPANY;
USE COMPANY;
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    FNAME VARCHAR(20) NOT NULL,
    SSN CHAR(9) NOT NULL,
    BDATE DATE,
    ADDRESS VARCHAR(30),
    SEX CHAR,
    SALARY DECIMAL(10 , 2 ),
    SUPER_SSN CHAR(9),
    DNO INT NOT NULL,
    PRIMARY KEY (SSN)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT (
	DNAME		VARCHAR(15) 	NOT NULL,
	DNUMBER		INT				NOT NULL,
	MGR_SSN		CHAR(9)			NOT NULL,
	NGR_START_DATE	DATE,
	PRIMARY KEY(DNUMBER),
	UNIQUE (DNAME),
	FOREIGN KEY (MGR_SSN) REFERENCES EMPLOYEE(SSN)
);

ALTER TABLE EMPLOYEE  ADD FOREIGN KEY  (SUPER_SSN) REFERENCES EMPLOYEE(SSN);
ALTER TABLE EMPLOYEE  ADD FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER);